basePath: /
definitions:
  controller.LoginBody:
    properties:
      password:
        example: password123
        format: string
        type: string
      username:
        example: test@test.com
        format: string
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: bipinmhr10@gmail.com
    name: Bipin Maharjan
  description: This is Go Email Service Build with Go-Fiber and Go-Imap
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Go Email Service API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login API
      parameters:
      - description: Login Body
        in: body
        name: RequestBody
        schema:
          $ref: '#/definitions/controller.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - Auth
  /logout:
    get:
      consumes:
      - application/json
      description: Logout API
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    description: Bearer token authorization
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
