basePath: /
definitions:
  controller.LoginBody:
    properties:
      host:
        example: outlook.office365.com
        type: string
      password:
        example: password1122
        format: string
        type: string
      port:
        example: "993"
        type: string
      username:
        example: test@test.com
        format: string
        type: string
    required:
    - host
    - password
    - port
    - username
    type: object
info:
  contact:
    email: bipinmhr10@gmail.com
    name: Bipin Maharjan
  description: This is Go Email Service Build with Go-Fiber and Go-Imap
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Go Email Service API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login API
      parameters:
      - description: Login Body
        in: body
        name: RequestBody
        schema:
          $ref: '#/definitions/controller.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - Auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: Logout API
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Logout
      tags:
      - Auth
  /message/preview:
    get:
      consumes:
      - application/json
      description: Get All Preview Message
      produces:
      - application/json
      responses: {}
      summary: Get All Preview Message
      tags:
      - Message
swagger: "2.0"
